app:
  host: ${APP_HOST:0.0.0.0}
  port: ${APP_PORT:8080}
  env: ${APP_ENV:production}
  debug: ${APP_DEBUG:false}
  timezone: ${APP_TIMEZONE:Asia/Shanghai}
  key: ${APP_KEY:}

log:
  level: ${LOG_LEVEL:info}
  stdout: ${LOG_STDOUT:false}

mysql:
  dsn: ${MYSQL_DSN:user:pass@tcp(127.0.0.1:3306)/dbname?charset=utf8mb4&parseTime=True}

wechat:
  officialAccount:
    appId: ${WECHAT_OA_APP_ID:xx}
    appSecret: ${WECHAT_OA_APP_SECRET:yy}
    token: ${WECHAT_OA_TOKEN:zz}
