app:
  host: ${APP_HOST:0.0.0.0}
  port: ${APP_PORT:8080}
  env: ${APP_ENV:production}
  debug: ${APP_DEBUG:false}
  timezone: Asia/Shanghai
  key: ${APP_KEY:}
  distRange: ${APP_DIST_RANGE:500}

log:
  level: ${LOG_LEVEL:info}
  stdout: ${LOG_STDOUT:false}

mysql:
  dsn: ${MYSQL_DSN:user:pass@tcp(127.0.0.1:3306)/dbname?charset=utf8mb4&parseTime=True}

redis:
  host: ${REDIS_HOST:127.0.0.1:6379}
  password: ${REDIS_PASSWORD:}
  db: ${REDIS_DB:0}
