app:
  host: ${APP_HOST:0.0.0.0}
  port: ${APP_PORT:8080}
  env: ${APP_ENV:production}
  debug: ${APP_DEBUG:false}
  timezone: ${APP_TIMEZONE:Asia/Shanghai}

log:
  level: ${LOG_LEVEL:info}
  stdout: ${LOG_STDOUT:false}

mysql:
  dsn: ${MYSQL_DSN:user:pass@tcp(127.0.0.1:3306)/dbname?charset=utf8mb4&parseTime=True}
